import { apiClient } from './api'
import type { ArxivPaper } from '../../types'

export interface URLExtractedContent {
  url: string
  title: string
  content: string
  extractedAt: Date
}

export async function extractWebContent(url: string): Promise<URLExtractedContent> {
  try {
    const response = await fetch(url)
    if (!response.ok) {
      throw new Error(`Failed to fetch URL: ${response.statusText}`)
    }

    const html = await response.text()

    const titleMatch = html.match(/<title>([^<]+)<\/title>/i)
    const title = titleMatch ? titleMatch[1].trim() : url

    const bodyMatch = html.match(/<body[^>]*>([\s\S]*?)<\/body>/i)
    const content = bodyMatch
      ? bodyMatch[1]
          .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, '')
          .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, '')
          .replace(/<[^>]+>/g, ' ')
          .replace(/\s+/g, ' ')
          .trim()
          .substring(0, 5000)
      : ''

    return {
      url,
      title,
      content,
      extractedAt: new Date()
    }
  } catch (error) {
    console.error('URL extraction error:', error)
    throw error
  }
}

export async function searchArxivForURL(url: string): Promise<ArxivPaper[]> {
  try {
    const content = await extractWebContent(url)
    const searchResults = await apiClient.searchArxiv(content.title, 5)
    return searchResults.papers
  } catch (error) {
    console.error('arXiv search error:', error)
    return []
  }
}

export async function createGitHubIssueFromCR(
  cr: string,
  repoUrl: string,
  title?: string
): Promise<{ url: string; issueNumber: number }> {
  try {
    const match = repoUrl.match(/github\.com\/([^/]+)\/([^/]+)/)
    if (!match) {
      throw new Error('Invalid GitHub repository URL')
    }

    const [, owner, repo] = match
    const githubApiUrl = `https://api.github.com/repos/${owner}/${repo}/issues`

    const issueTitle = title || cr.split('\n')[0].substring(0, 72)
    const issueBody = `## Change Request\n\n${cr}\n\n---\n*Generated by Cortex Evaluator*`

    const response = await fetch(githubApiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${localStorage.getItem('github_token') || ''}`
      },
      body: JSON.stringify({
        title: issueTitle,
        body: issueBody,
        labels: ['cr-evaluator']
      })
    })

    if (!response.ok) {
      const errorData = await response.json()
      throw new Error(errorData.message || 'Failed to create GitHub issue')
    }

    const issueData = await response.json()
    return {
      url: issueData.html_url,
      issueNumber: issueData.number
    }
  } catch (error) {
    console.error('GitHub issue creation error:', error)
    throw error
  }
}
