import type { MeetingSession } from '@/models';
import { formatDuration, formatDateTime, formatTime } from './format';

export function exportToMarkdown(meeting: MeetingSession): string {
  const lines: string[] = [];

  lines.push(`# ${meeting.title}`);
  lines.push('');

  lines.push('## Meeting Details');
  lines.push('');
  lines.push(`- **Date:** ${formatDateTime(meeting.createdAt)}`);
  lines.push(`- **Duration:** ${formatDuration(meeting.duration)}`);

  if (meeting.participants.length > 0) {
    lines.push(`- **Participants:** ${meeting.participants.map((p) => p.name).join(', ')}`);
  }

  if (meeting.tags.length > 0) {
    lines.push(`- **Tags:** ${meeting.tags.join(', ')}`);
  }

  lines.push('');

  if (meeting.analysis) {
    lines.push('## Summary');
    lines.push('');
    lines.push(meeting.analysis.summary);
    lines.push('');

    if (meeting.analysis.keyPoints.length > 0) {
      lines.push('## Key Points');
      lines.push('');
      meeting.analysis.keyPoints.forEach((point) => {
        lines.push(`- ${point.text}`);
      });
      lines.push('');
    }

    if (meeting.analysis.decisions.length > 0) {
      lines.push('## Decisions');
      lines.push('');
      meeting.analysis.decisions.forEach((decision) => {
        lines.push(`- ${decision.text}`);
        if (decision.context) {
          lines.push(`  - *Context:* ${decision.context}`);
        }
      });
      lines.push('');
    }

    if (meeting.analysis.actionItems.length > 0) {
      lines.push('## Action Items');
      lines.push('');
      meeting.analysis.actionItems.forEach((item) => {
        const checkbox = item.status === 'completed' ? '[x]' : '[ ]';
        let line = `- ${checkbox} ${item.text}`;
        if (item.assignee) line += ` *(${item.assignee})*`;
        if (item.dueDate) line += ` - Due: ${formatDateTime(item.dueDate)}`;
        lines.push(line);
      });
      lines.push('');
    }

    if (meeting.analysis.risks.length > 0) {
      lines.push('## Risks & Blockers');
      lines.push('');
      meeting.analysis.risks.forEach((risk) => {
        lines.push(`- **[${risk.severity.toUpperCase()}]** ${risk.text}`);
        if (risk.mitigation) {
          lines.push(`  - *Mitigation:* ${risk.mitigation}`);
        }
      });
      lines.push('');
    }

    if (meeting.analysis.followUps.length > 0) {
      lines.push('## Follow-ups');
      lines.push('');
      meeting.analysis.followUps.forEach((followUp) => {
        let line = `- ${followUp.text}`;
        if (followUp.assignee) line += ` *(${followUp.assignee})*`;
        lines.push(line);
      });
      lines.push('');
    }
  }

  lines.push('## Transcript');
  lines.push('');

  if (meeting.segments.length > 0) {
    let currentSpeaker = '';
    meeting.segments.forEach((segment) => {
      if (segment.speakerLabel !== currentSpeaker) {
        currentSpeaker = segment.speakerLabel;
        lines.push(`**${currentSpeaker}** *(${formatTime(segment.startTime)})*`);
      }
      lines.push(`> ${segment.text}`);
      lines.push('');
    });
  } else {
    lines.push('*No transcript available.*');
  }

  lines.push('');
  lines.push('---');
  lines.push(`*Generated by Cortex Assistant on ${formatDateTime(new Date().toISOString())}*`);

  return lines.join('\n');
}

export function exportToPlainText(meeting: MeetingSession): string {
  const lines: string[] = [];

  lines.push(meeting.title.toUpperCase());
  lines.push('='.repeat(meeting.title.length));
  lines.push('');

  lines.push(`Date: ${formatDateTime(meeting.createdAt)}`);
  lines.push(`Duration: ${formatDuration(meeting.duration)}`);

  if (meeting.participants.length > 0) {
    lines.push(`Participants: ${meeting.participants.map((p) => p.name).join(', ')}`);
  }

  lines.push('');

  if (meeting.analysis) {
    lines.push('SUMMARY');
    lines.push('-'.repeat(7));
    lines.push(meeting.analysis.summary);
    lines.push('');

    if (meeting.analysis.actionItems.length > 0) {
      lines.push('ACTION ITEMS');
      lines.push('-'.repeat(12));
      meeting.analysis.actionItems.forEach((item, i) => {
        const status = item.status === 'completed' ? '[DONE]' : '[TODO]';
        lines.push(`${i + 1}. ${status} ${item.text}`);
        if (item.assignee) lines.push(`   Assigned to: ${item.assignee}`);
        if (item.dueDate) lines.push(`   Due: ${formatDateTime(item.dueDate)}`);
      });
      lines.push('');
    }
  }

  lines.push('TRANSCRIPT');
  lines.push('-'.repeat(10));

  if (meeting.segments.length > 0) {
    meeting.segments.forEach((segment) => {
      lines.push(`[${formatTime(segment.startTime)}] ${segment.speakerLabel}: ${segment.text}`);
    });
  } else {
    lines.push('No transcript available.');
  }

  return lines.join('\n');
}

export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportMeetingAsMarkdown(meeting: MeetingSession): void {
  const content = exportToMarkdown(meeting);
  const filename = `${meeting.title.replace(/[^a-z0-9]/gi, '_')}_${new Date().toISOString().split('T')[0]}.md`;
  downloadFile(content, filename, 'text/markdown');
}

export function exportMeetingAsText(meeting: MeetingSession): void {
  const content = exportToPlainText(meeting);
  const filename = `${meeting.title.replace(/[^a-z0-9]/gi, '_')}_${new Date().toISOString().split('T')[0]}.txt`;
  downloadFile(content, filename, 'text/plain');
}

export function exportMeetingAsJSON(meeting: MeetingSession): void {
  const content = JSON.stringify(meeting, null, 2);
  const filename = `${meeting.title.replace(/[^a-z0-9]/gi, '_')}_${new Date().toISOString().split('T')[0]}.json`;
  downloadFile(content, filename, 'application/json');
}
